MvcOtobusBiletleme/MvcOtobusBiletleme/Controllers/CalisanTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOtobusBiletleme.Models.Siniflar;

namespace MvcOtobusBiletleme.Controllers
{
    [Authorize]
    [Authorize(Roles = "A")]
    public class CalisanTypeController : Controller
    {
        // GET: CalisanType
        Context c = new Context();
        public ActionResult Index()
        {
            var calisantype = c.CalisanTypes.Where(x => x.Durum == true).ToList();
            return View(calisantype);
        }
        [HttpGet]
        public ActionResult YeniCalisanType()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniCalisanType(CalisanType ct)
        {
            c.CalisanTypes.Add(ct);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CalisanTypeSil(int id)
        {
            var deger = c.CalisanTypes.Find(id);
            deger.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CalisanTypeGetir(int id)
        {
            var calisantyp = c.CalisanTypes.Find(id);
            return View("CalisanTypeGetir", calisantyp);
        }
        public ActionResult CalisanTypeGuncelle(CalisanType ct)
        {
            var calisan = c.CalisanTypes.Find(ct.ID);
            calisan.TipAd = ct.TipAd;
            calisan.Durum = ct.Durum;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CalisanlarDetay(int id)
        {
            var degerler = c.Calisanlars.Where(x => x.CalisanTypeid == id).ToList();
            var per = c.CalisanTypes.Where(x => x.ID == id).Select(y => y.TipAd).FirstOrDefault();
            ViewBag.p = per;
            return View(degerler);
        }

    }
}

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/CalisanType/CalisanTypeGetir.cshtml
@model MvcOtobusBiletleme.Models.Siniflar.CalisanType 
@{
    ViewBag.Title = "CalisanTypeGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Çalışan Tip Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("CalisanTypeGuncelle", "CalisanType", FormMethod.Post))
{
    @Html.HiddenFor(x => x.ID)
    @Html.LabelFor(x => x.TipAd)
    @Html.TextBoxFor(x => x.TipAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Durum)
    @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/CalisanType/CalisanlarDetay.cshtml
@using MvcOtobusBiletleme.Models.Siniflar
@model List<Calisanlar>
@{
    ViewBag.Title = "CalisanlarDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Personel Detay</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Personel Tipi: @ViewBag.p</li>
</ol>

<table class="table table-hover">
    <tr>
        <th>Personel</th>
        <th>Telefon</th>
        <th>Email</th>
        <th>Adres</th>
        <th>Kullanıcı Adı</th>
        <th>Şifre</th>
        <th>Personel Tipi</th>
        <th>Şube Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var u in Model)
    {
        <tr>
            <td>@u.Ad @u.Soyad</td>
            <td>@u.Telefon</td>
            <td>@u.Email</td>
            <td>@u.EvAdres</td>
            <td>@u.KullaniciAd</td>
            <td>@u.Sifre</td>
            <td>@u.CalisanType.TipAd</td>
            <td>@u.Subeler.SubeAd</td>
            <td>
                <a href="/Calisanlar/CalisanlarSil/@u.ID" class="btn btn-danger">Sil</a>
            </td>
            <td>
                <a href="/Calisanlar/CalisanlarGetir/@u.ID" class="btn btn-success">Güncelle</a>
            </td>
        </tr>
    }
</table>

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/CalisanType/Index.cshtml
@using MvcOtobusBiletleme.Models.Siniflar;
@model List<CalisanType>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Tip Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>

    </tr>
    @foreach (var c in Model)
    {
        <tr>
            <td>@c.ID</td>
            <td>@c.TipAd</td>
            <td>
                <a href="/CalisanType/CalisanTypeSil/@c.ID" class="btn btn-danger">Sil</a>
            </td>
            <td><a href="/CalisanType/CalisanTypeGetir/@c.ID" class="btn btn-success">Güncelle</a></td>
            <td><a href="/CalisanType/CalisanlarDetay/@c.ID" class="btn btn-default" style="background-color:lightcoral;color:white;">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/CalisanType/YeniCalisanType/" class="btn btn-info">Yeni Tip Ekle</a>

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/CalisanType/YeniCalisanType.cshtml
@model MvcOtobusBiletleme.Models.Siniflar.CalisanType
@{
    ViewBag.Title = "YeniCalisanType";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Çalışan Tipi Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.TipAd)
    @Html.TextBoxFor(x => x.TipAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Durum)
    @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Kaydet</button>

</form>