MvcOtobusBiletleme/MvcOtobusBiletleme/Models/Siniflar/Biletler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOtobusBiletleme.Models.Siniflar
{
    public class Biletler
    {
        [Key]
        public int Biletlerid { get; set; }
        public DateTime IslemZaman { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string YolcuAd { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string YolcuSoyad { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(5)]
        public string YolcuCinsiyet { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(15)]
        public string SatisMiRezarvasyonMu { get; set; }
        public DateTime KalkisZamani { get; set; }
        public int KoltukNo { get; set; }      
        public decimal Ucret { get; set; }
        public int Calisanlarid { get; set; }
        public int Musterilerid { get; set; }
        public int Seferlerid { get; set; }
        public virtual Calisanlar Calisanlar { get; set; }
        public virtual Musteriler Musteriler { get; set; }
        public virtual Seferler Seferler { get; set; }
    }
}

MvcOtobusBiletleme/MvcOtobusBiletleme/Controllers/BiletlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOtobusBiletleme.Models.Siniflar;

namespace MvcOtobusBiletleme.Controllers
{
    [Authorize]
    public class BiletlerController : Controller
    {
        //GET: Biletler
       Context c = new Context();
        public ActionResult Index()
        {
            var biletler = c.Biletlers.ToList();
            return View(biletler);
        }
        [HttpGet]
        public ActionResult YeniBiletler()
        {
            List<SelectListItem> degerler1 = (from x in c.Seferlers.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.SeferAd,
                                                  Value = x.ID.ToString()
                                              }).ToList();
            List<SelectListItem> degerler3 = (from x in c.Calisanlars.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Ad + " " + x.Soyad,
                                                  Value = x.ID.ToString()
                                              }).ToList();
            ViewBag.dgr1 = degerler1;
            ViewBag.dgr3 = degerler3;
            return View();
        }
        [HttpPost]
        public ActionResult YeniBiletler(Biletler b)
        {
            c.Biletlers.Add(b);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult BiletlerGetir(int id)
        {
            List<SelectListItem> degerler1 = (from x in c.Seferlers.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.SeferAd,
                                                  Value = x.ID.ToString()
                                              }).ToList();
            List<SelectListItem> degerler3 = (from x in c.Calisanlars.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Ad + " " + x.Soyad,
                                                  Value = x.ID.ToString()
                                              }).ToList();
            ViewBag.dgr1 = degerler1;
            ViewBag.dgr3 = degerler3;
            var deger = c.Biletlers.Find(id);
            return View("BiletlerGetir", deger);
        }
        public ActionResult BiletlerGuncelle(Biletler b)
        {
            var bilet = c.Biletlers.Find(b.Biletlerid);           
            bilet.IslemZaman = b.IslemZaman;
            bilet.YolcuCinsiyet = b.YolcuCinsiyet;
            bilet.SatisMiRezarvasyonMu = b.SatisMiRezarvasyonMu;
            bilet.KoltukNo = b.KoltukNo;
            bilet.YolcuAd = b.YolcuAd;
            bilet.YolcuSoyad = b.YolcuSoyad;
            bilet.Ucret = b.Ucret;
            bilet.Calisanlarid = b.Calisanlarid;
            bilet.Musterilerid = b.Musterilerid;
            bilet.Seferlerid = b.Seferlerid;
            bilet.KalkisZamani = b.KalkisZamani;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/Biletler/BiletlerGetir.cshtml
@model MvcOtobusBiletleme.Models.Siniflar.Biletler
@{
    ViewBag.Title = "BiletlerGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Bilet Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("BiletlerGuncelle", "Biletler", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Biletlerid)
    @Html.Label("Sefer")
    @Html.DropDownListFor(x => x.Seferlerid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Yolcu Ad")
    @Html.TextBoxFor(x => x.YolcuAd, new { @class = "form-control" })
    <br />
    @Html.Label("Yolcu Soyad")
    @Html.TextBoxFor(x => x.YolcuSoyad, new { @class = "form-control" })
    <br />
    @Html.Label("Cinsiyet")
    @Html.TextBoxFor(x => x.YolcuCinsiyet, new { @class = "form-control" })
    <br />
    @Html.Label("Yolcu Id")
    @Html.TextBoxFor(x => x.Musterilerid, new { @class = "form-control" })
    <br />
    @Html.Label("Koltuk No")
    @Html.TextBoxFor(x => x.KoltukNo, new { @class = "form-control" })
    <br />
    @Html.Label("Kalkış Zamanı")
    @Html.TextBoxFor(x => x.KalkisZamani, new { @class = "form-control" })
    <br />
    @Html.Label("Satış/Rezarvasyon")
    @Html.TextBoxFor(x => x.SatisMiRezarvasyonMu, new { @class = "form-control" })
    <br />
    @Html.Label("Ücret")
    @Html.TextBoxFor(x => x.Ucret, new { @class = "form-control" })
    <br />
    @Html.Label("İşlem Zamanı")
    @Html.TextBoxFor(x => x.IslemZaman, new { @class = "form-control" })
    <br />
    @Html.Label("Personel Ad Soyad")
    @Html.DropDownListFor(x => x.Calisanlarid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/Biletler/Index.cshtml
@using MvcOtobusBiletleme.Models.Siniflar;
@model List<Biletler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>Sefer</th>
            <th>Yolcu</th>
            <th>Cinsiyet</th>
            <th>Yolcu Id</th>
            <th>Koltuk Numarası</th>
            <th>Kalkış Zamanı</th>
            <th>Satış/Rezarvasyon</th>
            <th>Ücret</th>
            <th>İşlem Zamanı</th>
            <th>Personel Ad Soyad</th>
            <th>GÜNCELLE</th>

        </tr>
    </thead>
    @foreach (var u in Model)
    {
        <tr>
            <td>@u.Seferler.SeferAd</td>
            <td>@u.YolcuAd @u.YolcuSoyad</td>
            <td>@u.YolcuCinsiyet</td>
            <td>@u.Musteriler.ID</td>
            <td>@u.KoltukNo</td>
            <td>@u.KalkisZamani</td>
            <td>@u.SatisMiRezarvasyonMu</td>
            <td>@u.Ucret</td>
            <td>@u.IslemZaman</td>
            <td>@u.Calisanlar.Ad @u.Calisanlar.Soyad</td>
            <td>
                <a href="/Biletler/BiletlerGetir/@u.Biletlerid" class="btn btn-success">Güncelle</a>
            </td>
        </tr>
    }
</table>
<a href="/Biletler/YeniBiletler/" class="btn btn-info">Yeni Bilet Sat</a> <td>~</td>
<a href="/DoluKoltuk/Index/" class="btn btn-info">Dolu Koltuklar</a>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
<script>
    $('#tbl1').dataTable({});
</script>

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/Biletler/YeniBiletler.cshtml
@model MvcOtobusBiletleme.Models.Siniflar.Biletler
@{
    ViewBag.Title = "YeniBiletler";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Bilet Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Sefer")
    @Html.DropDownListFor(x => x.Seferlerid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Yolcu Ad")
    @Html.TextBoxFor(x => x.YolcuAd, new { @class = "form-control" })
    <br />
    @Html.Label("Yolcu Soyad")
    @Html.TextBoxFor(x => x.YolcuSoyad, new { @class = "form-control" })
    <br />
    @Html.Label("Cinsiyet")
    @Html.TextBoxFor(x => x.YolcuCinsiyet, new { @class = "form-control" })
    <br />
    @Html.Label("Yolcu Id")
    @Html.TextBoxFor(x => x.Musterilerid, new { @class = "form-control" })
    <br />
    @Html.Label("Koltuk No")
    @Html.TextBoxFor(x => x.KoltukNo, new { @class = "form-control" })
    <br />
    @Html.Label("Kalkış Zamanı")
    @Html.TextBoxFor(x => x.KalkisZamani, new { @class = "form-control" })
    <br />
    @Html.Label("Satış/Rezarvasyon")
    @Html.TextBoxFor(x => x.SatisMiRezarvasyonMu, new { @class = "form-control" })
    <br />
    @Html.Label("Ücret")
    @Html.TextBoxFor(x => x.Ucret, new { @class = "form-control" })
    <br />
    @Html.Label("İşlem Zamanı")
    @Html.TextBoxFor(x => x.IslemZaman, new { @class = "form-control" })
    <br />
    @Html.Label("Personel Ad Soyad")
    @Html.DropDownListFor(x => x.Calisanlarid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Kaydet</button>

</form>