MvcOtobusBiletleme/MvcOtobusBiletleme/Models/Siniflar/MasrafTipleri.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOtobusBiletleme.Models.Siniflar
{
    public class MasrafTipleri
    {
        [Key]
        public int ID { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string MasrafAd { get; set; }
        public bool Durum { get; set; }

        public ICollection<OtobusMasraflari> OtobusMasraflaris { get; set; }
    }
}

MvcOtobusBiletleme/MvcOtobusBiletleme/Controllers/MasrafTipleriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOtobusBiletleme.Models.Siniflar;

namespace MvcOtobusBiletleme.Controllers
{
    [Authorize]
    [Authorize(Roles = "A")]
    public class MasrafTipleriController : Controller
    {
        // GET: MasrafTipleri
        Context c = new Context();
        public ActionResult Index()
        {
            var masraftipleri = c.MasrafTipleris.Where(x => x.Durum == true).ToList();
            return View(masraftipleri);
        }
        [HttpGet]
        public ActionResult YeniMasrafTipleri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMasrafTipleri(MasrafTipleri ms)
        {
            c.MasrafTipleris.Add(ms);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MasrafTipleriSil(int id)
        {
            var deger = c.MasrafTipleris.Find(id);
            deger.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MasrafTipleriGetir(int id)
        {
            var masraftip = c.MasrafTipleris.Find(id);
            return View("MasrafTipleriGetir", masraftip);
        }
        public ActionResult MasrafTipleriGuncelle(MasrafTipleri ms)
        {
            var masraf = c.MasrafTipleris.Find(ms.ID);
            masraf.MasrafAd = ms.MasrafAd;
            masraf.Durum = ms.Durum;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/MasrafTipleri/Index.cshtml
@using MvcOtobusBiletleme.Models.Siniflar;
@model List<MasrafTipleri>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>Masraf Ad</th>
        <th>Sil</th>
        <th>Güncelle</th>

    </tr>
    @foreach (var u in Model)
    {
        <tr>
            <td>@u.MasrafAd</td>
            <td>
                <a href="/MasrafTipleri/MasrafTipleriSil/@u.ID" class="btn btn-danger">Sil</a>
            </td>
            <td>
                <a href="/MasrafTipleri/MasrafTipleriGetir/@u.ID" class="btn btn-success">Güncelle</a>
            </td>
        </tr>
    }
</table>
<a href="/MasrafTipleri/YeniMasrafTipleri/" class="btn btn-info">Yeni Masraf Tipi</a>

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/MasrafTipleri/MasrafTipleriGetir.cshtml
@model MvcOtobusBiletleme.Models.Siniflar.MasrafTipleri
@{
    ViewBag.Title = "MasrafTipleriGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Masraf Tipi Güncelleme Sayfası</h2>
<br />
@using (Html.BeginForm("MasrafTipleriGuncelle", "MasrafTipleri", FormMethod.Post))
{
    @Html.HiddenFor(x => x.ID)
    @Html.LabelFor(x => x.MasrafAd)
    @Html.TextBoxFor(x => x.MasrafAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Durum)
    @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/MasrafTipleri/YeniMasrafTipleri.cshtml
@model MvcOtobusBiletleme.Models.Siniflar.MasrafTipleri
@{
    ViewBag.Title = "YeniMasrafTipleri";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Masraf Tipi Ekleme Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.MasrafAd)
    @Html.TextBoxFor(x => x.MasrafAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Durum)
    @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Kaydet</button>

</form>