MvcOtobusBiletleme/MvcOtobusBiletleme/Models/Siniflar/OtobusMasraflari.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcOtobusBiletleme.Models.Siniflar
{
    public class OtobusMasraflari
    {
        [Key]
        public int ID { get; set; }
        public decimal Tutar { get; set; }
        public int Calisanlarid { get; set; }
        public int Otobuslerid { get; set; }
        public int MasrafTipleriid { get; set; }
        public int Seferlerid { get; set; }
        public virtual Calisanlar Calisanlar { get; set; }
        public virtual Otobusler Otobusler { get; set; }
        public virtual MasrafTipleri MasrafTipleri { get; set; }
        public virtual Seferler Seferler { get; set; }
    }
}

MvcOtobusBiletleme/MvcOtobusBiletleme/Controllers/OtobusMasraflariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOtobusBiletleme.Models.Siniflar;

namespace MvcOtobusBiletleme.Controllers
{
    [Authorize]
    [Authorize(Roles = "A")]
    public class OtobusMasraflariController : Controller
    {
        // GET: OtobusMasraflari
        Context c = new Context();
        public ActionResult Index()
        {
            var otobusmasraflari = c.OtobusMasraflaris.ToList();
            return View(otobusmasraflari);
        }
        [HttpGet]
        public ActionResult YeniOtobusMasraflari()
        {
            List<SelectListItem> degerler1 = (from x in c.Seferlers.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.SeferAd,
                                                  Value = x.ID.ToString()
                                              }).ToList();
            List<SelectListItem> degerler2 = (from x in c.Otobuslers.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Plaka,
                                                  Value = x.ID.ToString()
                                              }).ToList();
            List<SelectListItem> degerler3 = (from x in c.Calisanlars.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Ad + " " + x.Soyad,
                                                  Value = x.ID.ToString()
                                              }).ToList();
            List<SelectListItem> degerler4 = (from x in c.MasrafTipleris.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.MasrafAd,
                                                  Value = x.ID.ToString()
                                              }).ToList();    
            ViewBag.dgr1 = degerler1;
            ViewBag.dgr2 = degerler2;
            ViewBag.dgr3 = degerler3;
            ViewBag.dgr4 = degerler4;
            return View();
        }
        [HttpPost]
        public ActionResult YeniOtobusMasraflari(OtobusMasraflari om)
        {
            c.OtobusMasraflaris.Add(om);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult OtobusMasraflariGetir(int id)
        {
            List<SelectListItem> degerler1 = (from x in c.Seferlers.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.SeferAd,
                                                  Value = x.ID.ToString()
                                              }).ToList();
            List<SelectListItem> degerler2 = (from x in c.Otobuslers.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Plaka,
                                                  Value = x.ID.ToString()
                                              }).ToList();
            List<SelectListItem> degerler3 = (from x in c.Calisanlars.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.Ad + " " + x.Soyad,
                                                  Value = x.ID.ToString()
                                              }).ToList();
            List<SelectListItem> degerler4 = (from x in c.MasrafTipleris.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = x.MasrafAd,
                                                  Value = x.ID.ToString()
                                              }).ToList();            
            ViewBag.dgr1 = degerler1;
            ViewBag.dgr2 = degerler2;
            ViewBag.dgr3 = degerler3;
            ViewBag.dgr4 = degerler4;
            var otobusmas = c.OtobusMasraflaris.Find(id);
            return View("OtobusMasraflariGetir", otobusmas);
        }
        public ActionResult OtobusMasraflariGuncelle(OtobusMasraflari om)
        {
            var otobus = c.OtobusMasraflaris.Find(om.ID);
            otobus.Seferlerid = om.Seferlerid;
            otobus.Otobuslerid = om.Otobuslerid;            
            otobus.Calisanlarid = om.Calisanlarid;
            otobus.MasrafTipleriid = om.MasrafTipleriid;
            otobus.Tutar = om.Tutar;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/OtobusMasraflari/Index.cshtml
@using MvcOtobusBiletleme.Models.Siniflar;
@model List<OtobusMasraflari>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>Sefer Adı</th>
        <th>Otobüs</th>
        <th>Çalışan Şoför</th>
        <th>Masraf Tipi</th>
        <th>Tutar</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var om in Model)
    {
        <tr>
            <td>@om.Seferler.SeferAd</td>
            <td>@om.Otobusler.Plaka</td>
            <td>@om.Calisanlar.Ad @om.Calisanlar.Soyad</td>
            <td>@om.MasrafTipleri.MasrafAd</td>
            <td>@om.Tutar</td>
            <td>
                <a href="/OtobusMasraflari/OtobusMasraflariGetir/@om.ID" class="btn btn-success">Güncelle</a>
            </td>
        </tr>
    }
</table>
<a href="/OtobusMasraflari/YeniOtobusMasraflari/" class="btn btn-info">Yeni Otobüs Masrafi Ekle</a> <td>~</td>
<a href="/MasrafTipleri/Index/" class="btn btn-info">Yeni Masraf Tipi Ekle</a>

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/OtobusMasraflari/OtobusMasraflariGetir.cshtml
@model MvcOtobusBiletleme.Models.Siniflar.OtobusMasraflari
@{
    ViewBag.Title = "OtobusMasraflariGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Otobüs Masraflari Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("OtobusMasraflariGuncelle", "OtobusMasraflari", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.ID)
    @Html.Label("Sefer Adı")
    @Html.DropDownListFor(x => x.Seferlerid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Otobüs Plakası")
    @Html.DropDownListFor(x => x.Otobuslerid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.Label("Çalışan Adı (Şoför)")
    @Html.DropDownListFor(x => x.Calisanlarid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.Label("Masraf Tipi")
    @Html.DropDownListFor(x => x.MasrafTipleriid, (List<SelectListItem>)ViewBag.dgr4, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tutar)
    @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcOtobusBiletleme/MvcOtobusBiletleme/Views/OtobusMasraflari/YeniOtobusMasraflari.cshtml
@model MvcOtobusBiletleme.Models.Siniflar.OtobusMasraflari
@{
    ViewBag.Title = "YeniOtobusMasraflari";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Otobüs Masrafı</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Sefer Adı")
    @Html.DropDownListFor(x => x.Seferlerid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Otobüs Plakası")
    @Html.DropDownListFor(x => x.Otobuslerid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.Label("Çalışan Adı (Şoför)")
    @Html.DropDownListFor(x => x.Calisanlarid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.Label("Masraf Tipi")
    @Html.DropDownListFor(x => x.MasrafTipleriid, (List<SelectListItem>)ViewBag.dgr4, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tutar)
    @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Kaydet</button>

</form>